### ISSUE TITLE
Fix to System.ArgumentOutOfRangeException error

### ISSUE THREAD

**Issue by nothotscott** [Bitl/Novetus_src#1]
Verify `code.Length > pFrom.Length`  in 

```cs
public static string GetArgsFromTag(string code, string tag, string endtag)
{
	int pFrom = code.IndexOf(tag) + tag.Length;
	int pTo = code.LastIndexOf(endtag);

	string result = code.Substring(pFrom, pTo - pFrom);
		
	return result;
}
```

https://github.com/Bitl/Novetus_src/blob/ea6291c0736dcc10e08821e78df3764185093944/NovetusLauncher/NovetusFuncs/ClientScript.cs

**Comment by Bitl** [comment]
Fixed in the most recent commit. https://github.com/Bitl/Novetus_src/commit/7cd07f7944ab57711c0618aad6241f6bb74332a8
